#!/bin/bash

echo "$((5+6))"

function install(){
    #write code here
    local a = "a"
    echo "executing ${FUNCNAME} - start"
    echo "installing ${1}"
    echo "executing ${FUNCNAME} - end"
}

install "nginx"

## if you run some command and you are not able to find that the command that you ran is successful or not then after running that
# command you can run 

echo $?

# it give 0 if previous command is successful and give any other number other number than 0 if there is error in previous command.


## Test command
a = 5

test $a -eq 5

echo $?

## here -eq stands for equal. so by test command we can check any expression and if it is correct than echo $? gives 0.